DROP TABLE IF EXISTS USER;

CREATE TABLE IF NOT EXISTS USER(
    USER_NAME VARCHAR(30),
    PASSWD VARCHAR(100), 
    DOWNLOAD_PERMIT BOOL DEFAULT 'FALSE' NOT NULL, 
    NIGHT_MODE BOOL DEFAULT'FALSE' NOT NULL, 
    PRIMARY KEY (USER_NAME));